import Head from "next/head";

import Navbar from "./Components/Navbar";
import Header from "./Components/Header";
import Card from "./Components/Card";
import Card2 from "./Components/Card2";
import HeaderGrid from './Components/HeaderGrid';
import HeaderSidebar from './Components/HeaderSidebar';
import HeaderRightSidebar from './Components/HeaderRightSidebar';
import Modal from './Components/Modal';
import { useState } from "react";


export default function Home() {

    const [modal,setModal] = useState(false);
    
    const toggleModal=()=>{
      setModal(!modal);
    }

  return (
    <>
      <Head>
        <title>NextJS - Task 1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar toggleModal={toggleModal}/>
      <Header toggleModal={toggleModal}/>
      {modal?<><Modal toggleModal={toggleModal}/></>:null}
      <div className="mx-auto grid max-w-6xl grid-cols-12 gap-4 p-1">
        <HeaderGrid/>
        <HeaderSidebar/>
        <HeaderRightSidebar/>
        {/* <div className="footer col-span-12  border border-gray-800  p-6">
        </div> */}
      </div>

    </>
  );
}
